version: "3"
services:
    nginx:
        container_name: "nginx"
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - node
    node:
        container_name: "node"
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
    next:
        container_name: "next"
        restart: "on-failure"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - "./frontend:/usr/src/next"
            - "/usr/src/next/node_modules"
            - "/usr/src/next/.next"
        ports:
            - "3000:3000"

    # mysql:
    #     build: ./mysql
    #     restart: unless-stopped
    #     container_name: app_mysql
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/mysql_data:/var/lib/mysql
    #         - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 12345678
    #         MYSQL_DATABASE: doremifa
# version: "3"
# services:
#     nginx:
#         restart: always
#         image: achievedw/doremi-games-nginx
#         ports:
#             - "80:80"
#         depends_on:
#             - node

#     node:
#         image: achievedw/doremi-games-node
#         volumes:
#             - "./backend:/usr/src/node"
#             - "/usr/src/node/node_modules"
#         ports:
#             - "5000:5000"
#         env_file:
#             - ./backend/.env

#     next:
#         restart: "on-failure"
#         image: achievedw/doremi-games-next
#         volumes:
#             - "./frontend:/usr/src/next"
#             - "/usr/src/next/node_modules"
#             - "/usr/src/next/.next"
#         ports:
#             - "3000:3000"
#         env_file:
#             - ./frontend/.env
