version: "3"
services:
    nginx:
        restart: always
        image: achievedw/doremi-games-nginx
        ports:
            - "80:80"
        depends_on:
            - node

    node:
        image: achievedw/doremi-games-node
        volumes:
            - "./backend:/usr/src/node"
            - "/usr/src/node/node_modules"
        ports:
            - "5000:5000"
        env_file:
            - ./backend/.env

    next:
        restart: "on-failure"
        image: achievedw/doremi-games-next
        volumes:
            - "./frontend:/usr/src/next"
            - "/usr/src/next/node_modules"
            - "/usr/src/next/.next"
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
