version: "3"
services:
    node:
        image: achievedw/p2e-game-node:3.0

        ports:
            - "5000:5000"
        env_file:
            - ./backend/.env

    next:
        restart: "on-failure"
        image: achievedw/p2e-game-next:5.0

        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
    nginx:
        restart: always
        image: achievedw/p2e-game-nginx:4.0
        ports:
            - "80:80"
        depends_on:
            - node
            - next
