version: "3"
services:
    node:
        container_name: "node"
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
        ports:
            - "5000:5000"
    next:
        container_name: "next"
        restart: "on-failure"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        env_file:
            - ./frontend/.env
        ports:
            - "3000:3000"
    nginx:
        container_name: "nginx"
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - node
            - next
