version: "3"
services:
    nginx:
        container_name: "nginx"
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - node
    node:
        container_name: "node"
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
    next:
        container_name: "next"
        restart: "on-failure"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - "./frontend:/usr/src/next"
            - "/usr/src/next/node_modules"
            - "/usr/src/next/.next"
        ports:
            - "3000:3000"
