# This is a basic workflow to help you get started with Actions

name: Docker & AWS_EB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ kdw ]
  pull_request:
    branches: [ kdw ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: before install
        run: docker build -t achievedw/test-app -f Dockerfile.dev ./frontend

      # Runs a set of commands using the runners shell
      - name: build dockerfile
        run: |
          - docker build -t achievedw/docker-frontend ./frontend
          - docker build -t achievedw/docker-backend ./backend
          - docker build -t achievedw/docker-nginx ./nginx
      
      - name: login in docker-hub
        run:  echo "${{secrets.DOCKER_HUB_PASSWORD"}} | docker login -u "${{secrets.DOCKER_HUB_ID}}" --password-stdin
      
      - name: push docker images
        run: |
          - docker push achievedw/docker-frontend
          - docker push achievedw/docker-backend
          - docker push achievedw/docker-nginx
      
      - name: finished
        run: echo "success bu
