export const ActionTypes = {
  // /*** web3 ***/
  // WEB3_CONNECT_REQUEST: "WEB3_CONNECT_REQUEST",
  // WEB3_CONNECT_SUCCESS: "WEB3_CONNECT_SUCCESS",
  // WEB3_CONNECT_FAILED: "WEB3_CONNECT_FAILED",

  /*** 메타마스크 월렛 ***/
  METAMASK_W_CONNECT_REQUEST: "METAMASK_W_CONNECT_REQUEST",
  METAMASK_W_CONNECT_SUCCESS: "METAMASK_W_CONNECT_SUCCESS",
  METAMASK_W_CONNECT_FAILED: "METAMASK_W_CONNECT_FAILED",
  METAMASK_W_CONNECT_UPDATE: "METAMASK_W_CONNECT_UPDATE",

  /*** 바이낸스 월렛 ***/
  // BINANCE_W_CONNECT_REQUEST: "BINANCE_W_CONNECT_REQUEST",
  // BINANCE_W_CONNECT_SUCCESS: "BINANCE_W_CONNECT_SUCCESS",
  // BINANCE_W_CONNECT_FAILED: "BINANCE_W_CONNECT_FAILED",
  // BINANCE_W_CONNECT_UPDATE: "BINANCE_W_CONNECT_UPDATE",

  /*** 사용자 로그 ***/
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_LOGIN_UPDATE: "USER_LOGIN_UPDATE",
  USER_LOGIN_AUTH: "USER_LOGIN_AUTH",
  USER_LOGOUT: "USER_LOGOUT",

  /*** 사용자 정보 ***/
  // USER_DATA_REQUEST: "USER_DATA_REQUEST",
  // USER_DATA_SUCCESS: "USER_DATA_SUCCESS",
  // USER_DATA_FAILED: "USER_DATA_FAILED",
  // USER_DATA_UPDATE: "USER_DATA_UPDATE",

  /*** 컨트랙트 정보 ***/
  CONTRACT_DATA_REQUEST: "CONTRACT_DATA_REQUEST",
  CONTRACT_DATA_SUCCESS: "CONTRACT_DATA_SUCCESS",
  CONTRACT_DATA_FAILED: "CONTRACT_DATA_FAILED",
  CONTRACT_DATA_UPDATE: "CONTRACT_DATA_UPDATE",

  /*** 안내문구  ***/
  ALERT_UPDATE: "ALERT_UPDATE",
  ALERT_DELETE: "ALERT_DELETE",

}